stages:
 - test
 - doc
 - code_quality
 - examples
 - build
 - release
 - deploy

variables:
  COVERAGE_TYPE: "NotDymola"
  PAGES_BRANCH: main
  EXCLUDE_PYTHON: 37
  PYTHON_VERSION: "registry.git.rwth-aachen.de/ebc/ebc_all/gitlab_ci/templates:python_3.9"
  PYTHON_PACKAGE_NAME: "vclibpy"
  TEST_ENGINE: "PYTEST"
  GIT_REPO: "RWTH-EBC/vclibpy"
  EXAMPLE_CONVERTER_CONFIG: examples/converter.toml

include:
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'python/code-quality/pylint.gitlab-ci.yml'
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'python/doc/sphinxdoc.gitlab-ci.yml'
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'python/build/build.gitlab-ci.yml'
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'pages/gl-pages.gitlab-ci.yml'
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'pages/gh-pages.gitlab-ci.yml'
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'python/tests/tests.gitlab-ci.yml'
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'python/tests/coverage.gitlab-ci.yml'
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'python/pypi-release/release.gitlab-ci.yml'
  - project: 'ebc/ebc-general/templates/gitlab-ci'
    file: 'python/examples/examples.gitlab-ci.yml'
