general:
  time_step: 500.0
  gravity: 9.81
  alpha_0: 4200.0
  refrigerant: "R134a"

correlations:
  frost_density_choice: "D8"
  frost_thickness_choice: "jonas_diss"
  frost_conductivity_choice: "da_silva_paper"
  pressure_drop_choice: "Wang"
  h_conv_air_choice: "VDI"
  fan_choice: "OptiAbt"



# OptiAbt Optimum:
correction_factors:
  h_conv_air: 1.40
  h_conv_ref_2ph: 0.90
  betta_air: 1.40
  surface_density: 1.40
  k_frost: 0.90
  pressure_loss: 0.90


# Previous Global Optimum
# correction_factors:
#   h_conv_air: 1.30
#   h_conv_ref_2ph: 0.90
#   betta_air: 0.65
#   surface_density: 1.30
#   k_frost: 1.40
#   pressure_loss: 0.80



geometry:
  # Discretization / Model Splits
  # These control how the global geometry is sliced for the model
  register_amount: 8.0 
  layer_amount: 6

  # Number of Fans of the Evaporator Unit
  fan_amount: 2
  
  # Global Physical Dimensions (The Real Machine)
  total_fin_height: 1.2    # [m] Total height before splitting by registers
  total_fin_length: 0.15   # [m] Total length before splitting by layers
  
  # Detailed Geometry
  fin_pitch: 0.007
  fin_thickness: 0.0002
  fin_amount: 71
  fin_thermal_conductivity: 200.0
  
  tube_outer_diameter: 0.012
  tube_inner_diameter: 0.0114
  tube_thermal_conductivity: 400.0
  
  # Tube Layout (Global counts)
  total_tube_layers: 6
  total_tubes_per_layer: 24