general:
  time_step: 500.0
  gravity: 9.81
  alpha_0: 4200.0
  refrigerant: "R134a"

# OptiAbt Optimum neu:
correlations:
  frost_density_choice: "da_silva_paper"
  frost_conductivity_choice: "da_silva_paper"
  pressure_drop_choice: "Wang"
  h_conv_air_choice: "VDI" # "Jonas Diss"
  fan_choice: "OptiAbt"
correction_factors:
  h_conv_air: 0.85
  h_conv_ref_2ph: 1.25
  betta_air: 1.00
  surface_density: 0.70
  k_frost: 1.30
  frost_diffusion: 0.50
  pressure_loss: 1.00


# Combined Optimum:
# correlations:
#   frost_density_choice: "wang_2012" # "D8"
#   frost_conductivity_choice: "A"
#   pressure_drop_choice: "Wang"
#   h_conv_air_choice: "Wang" # "Jonas Diss"
#   fan_choice: "OptiAbt"
# correction_factors:
#   h_conv_air: 1.30
#   h_conv_ref_2ph: 0.70
#   betta_air: 0.50
#   surface_density: 0.70
#   k_frost: 1.30
#   frost_diffusion: 2.00
#   pressure_loss: 0.7

# Combined Optimum: 2.0
# correlations:
#   frost_density_choice: "D8" # "D8"
#   frost_conductivity_choice: "lee_1997"
#   pressure_drop_choice: "Wang"
#   h_conv_air_choice: "Wang" # "Jonas Diss"
#   fan_choice: "OptiAbt"
# correction_factors:
#   h_conv_air: 1.30
#   h_conv_ref_2ph: 0.95
#   betta_air: 0.50
#   surface_density: 0.70
#   k_frost: 0.85
#   frost_diffusion: 1.30
#   pressure_loss: 0.7

  # Abt Optimization
correlations:
  frost_density_choice: "da_silva_paper"
  frost_conductivity_choice: "lee_1997"
  pressure_drop_choice: "Wang"
  h_conv_air_choice: "VDI" # "Jonas Diss"
  fan_choice: "OptiAbt"
correction_factors:
  h_conv_air: 0.85
  h_conv_ref_2ph: 1.20
  betta_air: 1.30
  surface_density: 0.70
  k_frost: 1.30
  frost_diffusion: 0.70
  pressure_loss: 0.7


geometry:
  # Discretization / Model Splits
  # These control how the global geometry is sliced for the model
  register_amount: 8.0 
  layer_amount: 6

  # Number of Fans of the Evaporator Unit
  fan_amount: 2
  
  # Global Physical Dimensions (The Real Machine)
  total_fin_height: 1.2    # [m] Total height before splitting by registers
  total_fin_length: 0.15   # [m] Total length before splitting by layers
  
  # Detailed Geometry
  fin_pitch: 0.007
  fin_thickness: 0.0002
  fin_amount: 71
  fin_thermal_conductivity: 200.0
  
  tube_outer_diameter: 0.012
  tube_inner_diameter: 0.0114
  tube_thermal_conductivity: 400.0
  
  # Tube Layout (Global counts)
  total_tube_layers: 6
  total_tubes_per_layer: 24